[workspace]
resolver = "3"
members = [
  "crates/nuke-cli",
  "crates/nuke-eval",
  "crates/nuke-fixtures",
  "crates/nuke-grammar",
  "crates/nuke-lint",
  "crates/nuke-lsp",
  "crates/nuke-resolve",
  "crates/nuke-syntax",
  "crates/nuke-transpile",
]

[workspace.package]
version = "0.6.0"
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.85"

[workspace.dependencies]
nuke-eval = { path = "crates/nuke-eval" }
nuke-fixtures = { path = "crates/nuke-fixtures" }
nuke-grammar = { path = "crates/nuke-grammar" }
nuke-lint = { path = "crates/nuke-lint" }
nuke-lsp = { path = "crates/nuke-lsp" }
nuke-resolve = { path = "crates/nuke-resolve" }
nuke-syntax = { path = "crates/nuke-syntax" }
nuke-transpile = { path = "crates/nuke-transpile" }
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
clap_complete_nushell = "4"
clap_mangen = "0.3"
gix-config = { version = "0.59", features = ["sha1"] }
heck = "0.5"
indexmap = "2"
kdl = "6"
line-index = "0.1"
lsp-server = "0.7"
lsp-types = "0.95"
mlua = { version = "0.11", features = ["lua54", "vendored"] }
plist = "1"
quick-xml = "0.41"
rnix = "0.14"
rust-ini = { version = "0.21", features = ["inline-comment"] }
ryu = "1"
saphyr = "0.0.11"
serde ={ version = "1", default-features = false, features = ["std"] }
serde_json = "1"
tempfile = "3"
toml = { version = "0.9", features = ["preserve_order"] }

[workspace.lints.rust]
warnings = { level = "deny", priority = -1 }
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
