[package]
name = "nuke-transpile"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
heck.workspace = true
nuke-syntax.workspace = true
ryu.workspace = true
serde = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
gix-config.workspace = true
kdl.workspace = true
mlua.workspace = true
nuke-fixtures.workspace = true
plist.workspace = true
quick-xml.workspace = true
rnix.workspace = true
rust-ini.workspace = true
saphyr.workspace = true
serde_json.workspace = true
toml.workspace = true

[features]
serde = ["dep:serde", "nuke-syntax/serde"]

[[test]]
name = "binding"
required-features = ["serde"]

[lints]
workspace = true
