[package]
name = "nuke-eval"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
indexmap.workspace = true
nuke-syntax.workspace = true
serde = { workspace = true, optional = true }

[dev-dependencies]
nuke-fixtures.workspace = true
nuke-grammar.workspace = true
nuke-transpile.workspace = true
serde = { workspace = true, features = ["derive"] }
tempfile.workspace = true

[features]
serde = ["dep:serde", "nuke-syntax/serde"]

[[test]]
name = "binding"
required-features = ["serde"]

[lints]
workspace = true
