[package]
name = "nuke-grammar"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
abnf_to_pest = "0.6"
pest = "2"
pest_meta = "2"
pest_vm = "2"

[dev-dependencies]
abnf = "0.13"
nuke-fixtures.workspace = true

[lints]
workspace = true
