[package]
name = "nuke-cli"
version = "0.0.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "nuke"
path = "src/main.rs"

[dependencies]
clap.workspace = true
nuke-eval.workspace = true
nuke-lint.workspace = true
nuke-syntax.workspace = true
nuke-transpile.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
