[package]
name = "nuke-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "nuke"
path = "src/main.rs"

[dependencies]
clap.workspace = true
nuke-eval.workspace = true
nuke-lint.workspace = true
nuke-lsp.workspace = true
nuke-syntax.workspace = true
nuke-transpile.workspace = true

[dev-dependencies]
lsp-server.workspace = true
serde_json.workspace = true
tempfile.workspace = true

[lints]
workspace = true
